// The Airwindows effects, as device descriptors.
//
// GENERATED by build/devices/build-devices.mjs from the upstream sources pinned in
// devices.lock.json - do not edit.
//
// The names, the defaults and the count are read out of each plugin's own source, so what
// poptart shows beside a control is what the plugin calls it.
// 
// Every one is MIT, copyright Chris Johnson (airwindows.com), and says so in its descriptor;
// the About screen prints those lines from the catalog rather than from a list kept by hand.

import { defineDevice } from '../descriptor.mjs';

export const GALACTIC = defineDevice({
  "id": "Galactic",
  "kind": "fx",
  "version": 1,
  "description": "A very large reverb, pitched toward the unreal end.",
  "vendor": "Airwindows",
  "license": "MIT",
  "source": "https://github.com/airwindows/airwindows (Galactic)",
  "build": "wasm",
  "processor": "poptart-wasm-galactic",
  "channels": {
    "in": 2,
    "out": 2
  },
  "params": [
    {
      "id": "replace",
      "name": "Replace",
      "min": 0,
      "max": 1,
      "default": 0.5,
      "rate": "a",
      "group": "Controls",
      "description": "How much of the reverb tail is replaced by new sound as it decays, rather than being fed back. Low keeps a long tail going; high keeps the tail following what is played into it."
    },
    {
      "id": "brightness",
      "name": "Brightness",
      "min": 0,
      "max": 1,
      "default": 0.5,
      "rate": "a",
      "group": "Controls",
      "description": "How much high end survives each pass round the tank. Down is a dark hall; up is a bright metallic one."
    },
    {
      "id": "detune",
      "name": "Detune",
      "min": 0,
      "max": 1,
      "default": 0.5,
      "rate": "a",
      "group": "Controls",
      "description": "Pitch drift inside the tail, which is what stops a very long reverb ringing on one note. A little is a chorus on the tail; a lot is the unreal end of this device."
    },
    {
      "id": "bigness",
      "name": "Bigness",
      "min": 0,
      "max": 1,
      "default": 1,
      "rate": "a",
      "group": "Controls",
      "description": "The size of the space - how long the tail runs and how far apart its reflections are."
    },
    {
      "id": "drywet",
      "name": "Mix",
      "min": 0,
      "max": 1,
      "default": 1,
      "rate": "a",
      "group": "Controls",
      "description": "Dry against reverb."
    }
  ]
});

export const AIRWINDOWS_DEVICES = Object.freeze([GALACTIC]);
