// Cloud Seed, as a device descriptor.
//
// GENERATED by build/devices/build-devices.mjs from the upstream sources pinned in
// devices.lock.json - do not edit.
//
// The control names are written out in build/devices/cloudseed.mjs and the reason is there
// too; the defaults below are upstream's own factory program, read from its source.
// 
// MIT, copyright Ghost Note Engineering Ltd.

import { defineDevice } from '../descriptor.mjs';

export const CLOUDSEED = defineDevice({
  "id": "CloudSeed",
  "kind": "fx",
  "version": 1,
  "description": "A very large algorithmic reverb, for spaces that could not exist. Its defaults are upstream's own dark plate.",
  "vendor": "Ghost Note Engineering",
  "license": "MIT",
  "source": "https://github.com/GhostNoteAudio/CloudSeedCore",
  "build": "wasm",
  "processor": "poptart-wasm-cloudseed",
  "channels": {
    "in": 2,
    "out": 2
  },
  "params": [
    {
      "id": "interpolation",
      "name": "Interpolation",
      "group": "Input",
      "min": 0,
      "max": 1,
      "step": 1,
      "default": 1,
      "rate": "a",
      "description": "Smooths the delay lines as they are modulated, so a moving line glides instead of stepping. Off is cheaper and grainier."
    },
    {
      "id": "lowcuton",
      "name": "Low Cut On",
      "group": "Input",
      "min": 0,
      "max": 1,
      "step": 1,
      "default": 1,
      "rate": "a",
      "description": "Whether the low cut below is in the path at all."
    },
    {
      "id": "highcuton",
      "name": "High Cut On",
      "group": "Input",
      "min": 0,
      "max": 1,
      "step": 1,
      "default": 0,
      "rate": "a",
      "description": "Whether the high cut below is in the path at all."
    },
    {
      "id": "inputmix",
      "name": "Input Mix",
      "group": "Input",
      "min": 0,
      "max": 1,
      "default": 0.2346999943256378,
      "rate": "a",
      "description": "How much the two channels are summed before the reverb. Up is a mono feed into the tank, which keeps the tail centered; down keeps the sides apart."
    },
    {
      "id": "lowcut",
      "name": "Low Cut",
      "group": "Input",
      "min": 0,
      "max": 1,
      "default": 0.6399999856948853,
      "rate": "a",
      "description": "Takes the bottom off what goes INTO the tank, so low notes do not turn the tail to mud."
    },
    {
      "id": "highcut",
      "name": "High Cut",
      "group": "Input",
      "min": 0,
      "max": 1,
      "default": 0.2933000028133392,
      "rate": "a",
      "description": "Takes the top off what goes into the tank, which is most of what makes this reverb dark."
    },
    {
      "id": "dry",
      "name": "Dry",
      "group": "Output",
      "min": 0,
      "max": 1,
      "default": 0.8705999851226807,
      "rate": "a",
      "description": "The untouched signal. This is a reverb with separate dry, early and late levels rather than one mix knob."
    },
    {
      "id": "early",
      "name": "Early Level",
      "group": "Output",
      "min": 0,
      "max": 1,
      "default": 0,
      "rate": "a",
      "description": "The level of the early reflections - the taps and the early diffuser, which are the first thing you hear back."
    },
    {
      "id": "late",
      "name": "Late Level",
      "group": "Output",
      "min": 0,
      "max": 1,
      "default": 0.6613999605178833,
      "rate": "a",
      "description": "The level of the tail: the delay lines that go on feeding each other after the early reflections have gone."
    },
    {
      "id": "tapon",
      "name": "Tap On",
      "group": "Multitap",
      "min": 0,
      "max": 1,
      "step": 1,
      "default": 0,
      "rate": "a",
      "description": "Whether the multitap stage runs. It is the first set of reflections, before any diffusion."
    },
    {
      "id": "tapcount",
      "name": "Tap Count",
      "group": "Multitap",
      "min": 0,
      "max": 1,
      "default": 0.1959999948740005,
      "rate": "a",
      "description": "How many discrete echoes the multitap stage makes. A few is a slapback; many is the start of a room."
    },
    {
      "id": "tapdecay",
      "name": "Tap Decay",
      "group": "Multitap",
      "min": 0,
      "max": 1,
      "default": 1,
      "rate": "a",
      "description": "How much quieter each tap is than the one before it."
    },
    {
      "id": "tappredelay",
      "name": "Tap Predelay",
      "group": "Multitap",
      "min": 0,
      "max": 1,
      "default": 0,
      "rate": "a",
      "description": "How long before the first tap arrives - the gap between the sound and the space answering it."
    },
    {
      "id": "taplength",
      "name": "Tap Length",
      "group": "Multitap",
      "min": 0,
      "max": 1,
      "default": 0.9866999983787537,
      "rate": "a",
      "description": "How far apart the taps are spread in time, which is what reads as the size of the room."
    },
    {
      "id": "earlydiffuseon",
      "name": "Early Diffuse On",
      "group": "Early",
      "min": 0,
      "max": 1,
      "step": 1,
      "default": 0,
      "rate": "a",
      "description": "Whether the early reflections are smeared by an allpass chain. Off leaves them as distinct echoes."
    },
    {
      "id": "earlystages",
      "name": "Early Stages",
      "group": "Early",
      "min": 0,
      "max": 1,
      "default": 0.2960000038146973,
      "rate": "a",
      "description": "How many allpass stages the early diffuser runs. More smears the reflections further into a wash."
    },
    {
      "id": "earlydelay",
      "name": "Early Delay",
      "group": "Early",
      "min": 0,
      "max": 1,
      "default": 0.3066999912261963,
      "rate": "a",
      "description": "The length of each early allpass stage, which sets the grain of that smear."
    },
    {
      "id": "earlymodamount",
      "name": "Early Mod Amount",
      "group": "Early",
      "min": 0,
      "max": 1,
      "default": 0.143899992108345,
      "rate": "a",
      "description": "How far the early stages are wobbled, which stops them ringing on one note."
    },
    {
      "id": "earlyfeedback",
      "name": "Early Feedback",
      "group": "Early",
      "min": 0,
      "max": 1,
      "default": 0.7706999778747559,
      "rate": "a",
      "description": "How much of the early diffuser is fed back into itself - how long that first wash lasts."
    },
    {
      "id": "earlymodrate",
      "name": "Early Mod Rate",
      "group": "Early",
      "min": 0,
      "max": 1,
      "default": 0.2466999888420105,
      "rate": "a",
      "description": "How fast that wobble runs."
    },
    {
      "id": "latemode",
      "name": "Late Mode",
      "group": "Late",
      "min": 0,
      "max": 1,
      "default": 1,
      "rate": "a",
      "description": "How the late lines are wired: in parallel, or each one feeding the next."
    },
    {
      "id": "latelines",
      "name": "Late Lines",
      "group": "Late",
      "min": 0,
      "max": 1,
      "default": 1,
      "rate": "a",
      "description": "How many delay lines make the tail. More is a denser and smoother tail for more work."
    },
    {
      "id": "latediffuseon",
      "name": "Late Diffuse On",
      "group": "Late",
      "min": 0,
      "max": 1,
      "step": 1,
      "default": 1,
      "rate": "a",
      "description": "Whether the tail is smeared by allpasses as well as delayed."
    },
    {
      "id": "latestages",
      "name": "Late Stages",
      "group": "Late",
      "min": 0,
      "max": 1,
      "default": 0.4879999756813049,
      "rate": "a",
      "description": "How many allpass stages that smear uses."
    },
    {
      "id": "latesize",
      "name": "Late Size",
      "group": "Late",
      "min": 0,
      "max": 1,
      "default": 0.4693999886512756,
      "rate": "a",
      "description": "The length of the late delay lines: the size of the space the tail is running round."
    },
    {
      "id": "latelinemodamount",
      "name": "Late Line Mod Amount",
      "group": "Late",
      "min": 0,
      "max": 1,
      "default": 0.2719999849796295,
      "rate": "a",
      "description": "How far the late delay lines are wobbled, which is what keeps a very long tail from settling into a ringing tone."
    },
    {
      "id": "latedelay",
      "name": "Late Delay",
      "group": "Late",
      "min": 0,
      "max": 1,
      "default": 0.239999994635582,
      "rate": "a",
      "description": "The length of each late allpass stage."
    },
    {
      "id": "latediffusemodamount",
      "name": "Late Diffuse Mod Amount",
      "group": "Late",
      "min": 0,
      "max": 1,
      "default": 0.1467999964952469,
      "rate": "a",
      "description": "How far the late diffuser is wobbled, on top of the lines."
    },
    {
      "id": "latedecay",
      "name": "Late Decay",
      "group": "Late",
      "min": 0,
      "max": 1,
      "default": 0.6345999836921692,
      "rate": "a",
      "description": "How long the tail runs for. Near the top it barely decays at all, which is what this reverb is for."
    },
    {
      "id": "latelinemodrate",
      "name": "Late Line Mod Rate",
      "group": "Late",
      "min": 0,
      "max": 1,
      "default": 0.2292999923229218,
      "rate": "a",
      "description": "How fast the delay lines wobble."
    },
    {
      "id": "latefeedback",
      "name": "Late Feedback",
      "group": "Late",
      "min": 0,
      "max": 1,
      "default": 0.8506999611854553,
      "rate": "a",
      "description": "How much of the tail is fed back into the lines - density rather than length."
    },
    {
      "id": "latediffusemodrate",
      "name": "Late Diffuse Mod Rate",
      "group": "Late",
      "min": 0,
      "max": 1,
      "default": 0.1666999906301498,
      "rate": "a",
      "description": "How fast the late diffuser wobbles."
    },
    {
      "id": "lowshelfon",
      "name": "Low Shelf On",
      "group": "Equalizer",
      "min": 0,
      "max": 1,
      "step": 1,
      "default": 0,
      "rate": "a",
      "description": "Whether the low shelf below is in the tail\u2019s feedback path."
    },
    {
      "id": "highshelfon",
      "name": "High Shelf On",
      "group": "Equalizer",
      "min": 0,
      "max": 1,
      "step": 1,
      "default": 1,
      "rate": "a",
      "description": "Whether the high shelf below is in the tail\u2019s feedback path."
    },
    {
      "id": "lowpasson",
      "name": "Lowpass On",
      "group": "Equalizer",
      "min": 0,
      "max": 1,
      "step": 1,
      "default": 0,
      "rate": "a",
      "description": "Whether the lowpass below is in the tail\u2019s feedback path. This is the usual way to make a tail darken as it decays."
    },
    {
      "id": "lowfreq",
      "name": "Low Freq",
      "group": "Equalizer",
      "min": 0,
      "max": 1,
      "default": 0.3879999816417694,
      "rate": "a",
      "description": "Where the low shelf sits."
    },
    {
      "id": "highfreq",
      "name": "High Freq",
      "group": "Equalizer",
      "min": 0,
      "max": 1,
      "default": 0.5133999586105347,
      "rate": "a",
      "description": "Where the high shelf sits."
    },
    {
      "id": "cutoff",
      "name": "Cutoff",
      "group": "Equalizer",
      "min": 0,
      "max": 1,
      "default": 0.9759999513626099,
      "rate": "a",
      "description": "Where the lowpass sits. Because it is inside the feedback, every pass round the tank takes more top off - so the tail gets darker as it goes rather than starting dark."
    },
    {
      "id": "lowgain",
      "name": "Low Gain",
      "group": "Equalizer",
      "min": 0,
      "max": 1,
      "default": 0.5559999942779541,
      "rate": "a",
      "description": "How much the low shelf lifts or cuts, per pass round the tank."
    },
    {
      "id": "highgain",
      "name": "High Gain",
      "group": "Equalizer",
      "min": 0,
      "max": 1,
      "default": 0.7680000066757202,
      "rate": "a",
      "description": "How much the high shelf lifts or cuts, per pass round the tank."
    },
    {
      "id": "crossseed",
      "name": "Cross Seed",
      "group": "Equalizer",
      "min": 0,
      "max": 1,
      "default": 0,
      "rate": "a",
      "description": "How different the left and right sides are. Zero is the same space in both ears; up is two related spaces, which is what makes a wide tail."
    },
    {
      "id": "tapseed",
      "name": "Tap Seed",
      "group": "Seeds",
      "min": 0,
      "max": 1,
      "default": 0.3339999914169312,
      "rate": "a",
      "description": "Which random arrangement the multitap stage uses. Changing it rearranges the echoes without changing any of the settings above."
    },
    {
      "id": "diffusionseed",
      "name": "Diffusion Seed",
      "group": "Seeds",
      "min": 0,
      "max": 1,
      "default": 0.1850000023841858,
      "rate": "a",
      "description": "Which random arrangement the early diffuser uses."
    },
    {
      "id": "delayseed",
      "name": "Delay Seed",
      "group": "Seeds",
      "min": 0,
      "max": 1,
      "default": 0.2180999964475632,
      "rate": "a",
      "description": "Which random arrangement the late delay lines use."
    },
    {
      "id": "latediffusionseed",
      "name": "Late Diffusion Seed",
      "group": "Seeds",
      "min": 0,
      "max": 1,
      "default": 0.3652999997138977,
      "rate": "a",
      "description": "Which random arrangement the late diffuser uses."
    }
  ]
});

export const CLOUDSEED_DEVICES = Object.freeze([CLOUDSEED]);
