// The Mutable Instruments modules, as device descriptors.
//
// GENERATED by build/devices/build-devices.mjs from the upstream sources pinned in
// devices.lock.json - do not edit.
//
// Which modules can be ported at all - and which are analog hardware with no DSP to port -
// is written down in build/devices/mutable.mjs, along with why.
// 
// MIT, copyright Emilie Gillet, taken from each file's own header: the repository itself
// declares no license.

import { defineDevice } from '../descriptor.mjs';

export const PLAITS = defineDevice({
  "id": "Plaits",
  "kind": "synth",
  "version": 1,
  "description": "A macro oscillator with twenty-four synthesis models behind three controls, plus its own low-pass gate. Monophonic, as the module is.",
  "vendor": "Mutable Instruments",
  "license": "MIT",
  "source": "https://github.com/pichenettes/eurorack (plaits)",
  "build": "wasm",
  "processor": "poptart-wasm-plaits",
  "channels": {
    "in": 0,
    "out": 2
  },
  "params": [
    {
      "rate": "k",
      "id": "engine",
      "name": "Engine",
      "default": 8,
      "options": [
        "VA VCF",
        "Phase Distortion",
        "FM 6-op A",
        "FM 6-op B",
        "FM 6-op C",
        "Wave Terrain",
        "String Machine",
        "Chiptune",
        "Virtual Analog",
        "Waveshaping",
        "FM",
        "Grain",
        "Additive",
        "Wavetable",
        "Chord",
        "Speech",
        "Swarm",
        "Noise",
        "Particle",
        "String",
        "Modal",
        "Bass Drum",
        "Snare Drum",
        "Hi-Hat"
      ],
      "group": "Engine",
      "description": "Which synthesis model runs. Every other control means something different in each."
    },
    {
      "rate": "a",
      "id": "harmonics",
      "name": "Harmonics",
      "min": 0,
      "max": 1,
      "default": 0.5,
      "group": "Engine",
      "description": "The first of the three model controls. Broadly: how much material there is - the number of partials, the spread of a chord, the depth of the FM. It means something different in every engine."
    },
    {
      "rate": "a",
      "id": "timbre",
      "name": "Timbre",
      "min": 0,
      "max": 1,
      "default": 0.5,
      "group": "Engine",
      "description": "The second model control. Broadly: brightness, or the balance of what Harmonics set up. It means something different in every engine."
    },
    {
      "rate": "a",
      "id": "morph",
      "name": "Morph",
      "min": 0,
      "max": 1,
      "default": 0.5,
      "group": "Engine",
      "description": "The third model control. Broadly: the character of the waveform itself, often from soft to hard. It means something different in every engine."
    },
    {
      "rate": "a",
      "id": "blend",
      "name": "Blend",
      "min": 0,
      "max": 1,
      "default": 0,
      "group": "Engine",
      "description": "Plaits has two outputs, a main and a variation. Zero is the main one, one is the variation, in between is a mix."
    },
    {
      "rate": "a",
      "id": "decay",
      "name": "Decay",
      "min": 0,
      "max": 1,
      "default": 0.5,
      "group": "Envelope",
      "description": "How long the internal low-pass gate holds after a note starts."
    },
    {
      "rate": "a",
      "id": "lpgcolor",
      "name": "LPG Color",
      "min": 0,
      "max": 1,
      "default": 0.5,
      "group": "Envelope",
      "description": "How much the gate closes the tone as well as the level. Zero is a plain volume envelope."
    },
    {
      "rate": "a",
      "id": "fmamount",
      "name": "FM Amount",
      "min": 0,
      "max": 1,
      "default": 0,
      "group": "Modulation",
      "description": "How far a signal patched into the pitch bends it."
    },
    {
      "rate": "a",
      "id": "timbremod",
      "name": "Timbre Mod",
      "min": 0,
      "max": 1,
      "default": 0,
      "group": "Modulation",
      "description": "How much a signal patched into Timbre moves it, and which way round."
    },
    {
      "rate": "a",
      "id": "morphmod",
      "name": "Morph Mod",
      "min": 0,
      "max": 1,
      "default": 0,
      "group": "Modulation",
      "description": "How much a signal patched into Morph moves it, and which way round."
    }
  ]
});

export const RINGS = defineDevice({
  "id": "Rings",
  "kind": "synth",
  "version": 1,
  "description": "A resonator, struck by its own exciter. Six models from a plain modal bar to a string with a reverb behind it.",
  "vendor": "Mutable Instruments",
  "license": "MIT",
  "source": "https://github.com/pichenettes/eurorack (rings)",
  "build": "wasm",
  "processor": "poptart-wasm-rings",
  "channels": {
    "in": 0,
    "out": 2
  },
  "params": [
    {
      "rate": "k",
      "id": "model",
      "name": "Model",
      "default": 0,
      "options": [
        "Modal",
        "Sympathetic String",
        "String",
        "FM Voice",
        "Quantised Sympathetic",
        "String and Reverb"
      ],
      "group": "Resonator",
      "description": "Which resonator is struck. The last two are the module's own extended models."
    },
    {
      "rate": "a",
      "id": "structure",
      "name": "Structure",
      "min": 0,
      "max": 1,
      "default": 0.35,
      "group": "Resonator",
      "description": "What the resonator IS: the ratio of its partials, from a string through a bar to a bell. This is the control that decides whether it sounds struck or bowed material."
    },
    {
      "rate": "a",
      "id": "brightness",
      "name": "Brightness",
      "min": 0,
      "max": 1,
      "default": 0.5,
      "group": "Resonator",
      "description": "How much high end the resonator keeps, and how hard the exciter hits it."
    },
    {
      "rate": "a",
      "id": "damping",
      "name": "Damping",
      "min": 0,
      "max": 1,
      "default": 0.5,
      "group": "Resonator",
      "description": "How long the resonator rings on after it is struck."
    },
    {
      "rate": "a",
      "id": "position",
      "name": "Position",
      "min": 0,
      "max": 1,
      "default": 0.25,
      "group": "Resonator",
      "description": "Where along the resonator it is struck. Near the middle is round and fundamental-heavy; near the end is thin and full of odd partials."
    },
    {
      "rate": "k",
      "id": "polyphony",
      "name": "Polyphony",
      "min": 1,
      "max": 4,
      "default": 1,
      "step": 1,
      "group": "Resonator",
      "description": "How many notes can ring at once. More voices means each one is thinner, which is the module's own trade."
    },
    {
      "rate": "a",
      "id": "blend",
      "name": "Blend",
      "min": 0,
      "max": 1,
      "default": 0,
      "group": "Resonator",
      "description": "Rings has two outputs, odd and even. Zero is the first, one is the second."
    }
  ]
});

export const ELEMENTS = defineDevice({
  "id": "Elements",
  "kind": "synth",
  "version": 1,
  "description": "A modal resonator with three exciters in front of it: a bow, a breath and a mallet. Monophonic, as the module is.",
  "vendor": "Mutable Instruments",
  "license": "MIT",
  "source": "https://github.com/pichenettes/eurorack (elements)",
  "build": "wasm",
  "processor": "poptart-wasm-elements",
  "channels": {
    "in": 0,
    "out": 2
  },
  "params": [
    {
      "rate": "a",
      "id": "contour",
      "name": "Contour",
      "min": 0,
      "max": 1,
      "default": 0.5,
      "group": "Envelope",
      "description": "The shape of the envelope every exciter follows, from a short pluck to a held swell."
    },
    {
      "rate": "a",
      "id": "bowlevel",
      "name": "Bow Level",
      "min": 0,
      "max": 1,
      "default": 0,
      "group": "Bow",
      "description": "How hard the resonator is bowed - a continuous exciter, so it sounds for as long as the note is held."
    },
    {
      "rate": "a",
      "id": "bowtimbre",
      "name": "Bow Timbre",
      "min": 0,
      "max": 1,
      "default": 0.5,
      "group": "Bow",
      "description": "The grain of the bow, from a smooth draw to a scratch."
    },
    {
      "rate": "a",
      "id": "blowlevel",
      "name": "Blow Level",
      "min": 0,
      "max": 1,
      "default": 0,
      "group": "Blow",
      "description": "How hard the resonator is blown - a noise and particle exciter, between a breath and a wind instrument."
    },
    {
      "rate": "a",
      "id": "blowmeta",
      "name": "Blow Flow",
      "min": 0,
      "max": 1,
      "default": 0.5,
      "group": "Blow",
      "description": "What the blowing IS, sweeping from a granular stream through noise to a pitched jet."
    },
    {
      "rate": "a",
      "id": "blowtimbre",
      "name": "Blow Timbre",
      "min": 0,
      "max": 1,
      "default": 0.5,
      "group": "Blow",
      "description": "The brightness of that breath."
    },
    {
      "rate": "a",
      "id": "strikelevel",
      "name": "Strike Level",
      "min": 0,
      "max": 1,
      "default": 0.8,
      "group": "Strike",
      "description": "How hard the resonator is struck - the percussive exciter, one hit per note."
    },
    {
      "rate": "a",
      "id": "strikemeta",
      "name": "Strike Mallet",
      "min": 0,
      "max": 1,
      "default": 0.5,
      "group": "Strike",
      "description": "What the mallet is, from a soft particle burst through a hard hit to a sample-like click."
    },
    {
      "rate": "a",
      "id": "striketimbre",
      "name": "Strike Timbre",
      "min": 0,
      "max": 1,
      "default": 0.5,
      "group": "Strike",
      "description": "The brightness and hardness of that strike."
    },
    {
      "rate": "a",
      "id": "signature",
      "name": "Signature",
      "min": 0,
      "max": 1,
      "default": 0,
      "group": "Strike",
      "description": "Adds the module's own noise and inharmonicity to the exciters, which is what stops it sounding like a clean physical model."
    },
    {
      "rate": "a",
      "id": "geometry",
      "name": "Geometry",
      "min": 0,
      "max": 1,
      "default": 0.4,
      "group": "Resonator",
      "description": "What the resonator is made of and shaped like, sweeping through plates, strings, bars and tubes. Everything else is heard through this."
    },
    {
      "rate": "a",
      "id": "brightness",
      "name": "Brightness",
      "min": 0,
      "max": 1,
      "default": 0.6,
      "group": "Resonator",
      "description": "How much high end the resonator keeps."
    },
    {
      "rate": "a",
      "id": "damping",
      "name": "Damping",
      "min": 0,
      "max": 1,
      "default": 0.7,
      "group": "Resonator",
      "description": "How long it rings on. Near the top it barely decays, which is the drone end of this module."
    },
    {
      "rate": "a",
      "id": "position",
      "name": "Position",
      "min": 0,
      "max": 1,
      "default": 0.3,
      "group": "Resonator",
      "description": "Where the exciters meet the resonator, which decides which partials are fed and which are missed."
    },
    {
      "rate": "a",
      "id": "space",
      "name": "Space",
      "min": 0,
      "max": 1,
      "default": 0.2,
      "group": "Output",
      "description": "The reverb built into the module, from a small room to a diffuse wash."
    },
    {
      "rate": "a",
      "id": "blend",
      "name": "Blend",
      "min": 0,
      "max": 1,
      "default": 0,
      "group": "Output",
      "description": "Elements has two outputs, the resonator and the raw exciter. Zero is the resonator."
    }
  ]
});

export const BRAIDS = defineDevice({
  "id": "Braids",
  "kind": "synth",
  "version": 1,
  "description": "The macro oscillator that came before Plaits: forty-eight models behind two controls, with a simpler character and its own attack-decay envelope.",
  "vendor": "Mutable Instruments",
  "license": "MIT",
  "source": "https://github.com/pichenettes/eurorack (braids)",
  "build": "wasm",
  "processor": "poptart-wasm-braids",
  "channels": {
    "in": 0,
    "out": 2
  },
  "params": [
    {
      "rate": "k",
      "id": "shape",
      "name": "Shape",
      "default": 2,
      "options": [
        "CSaw",
        "Morph",
        "Saw Square",
        "Sine Triangle",
        "Buzz",
        "Square Sub",
        "Saw Sub",
        "Square Sync",
        "Saw Sync",
        "Triple Saw",
        "Triple Square",
        "Triple Triangle",
        "Triple Sine",
        "Triple Ring Mod",
        "Saw Swarm",
        "Saw Comb",
        "Toy",
        "Filter LP",
        "Filter Peak",
        "Filter BP",
        "Filter HP",
        "VOSIM",
        "Vowel",
        "Vowel FOF",
        "Harmonics",
        "FM",
        "Feedback FM",
        "Chaotic FM",
        "Plucked",
        "Bowed",
        "Blown",
        "Fluted",
        "Struck Bell",
        "Struck Drum",
        "Kick",
        "Cymbal",
        "Snare",
        "Wavetables",
        "Wave Map",
        "Wave Line",
        "Wave Paraphonic",
        "Filtered Noise",
        "Twin Peaks Noise",
        "Clocked Noise",
        "Granular Cloud",
        "Particle Noise",
        "Digital Modulation",
        "Question Mark"
      ],
      "group": "Oscillator",
      "description": "Which of the forty-eight models runs. Timbre and Color mean something different in each."
    },
    {
      "rate": "a",
      "id": "timbre",
      "name": "Timbre",
      "min": 0,
      "max": 1,
      "default": 0.5,
      "group": "Oscillator",
      "description": "The first of the two model controls. What it does depends entirely on which of the forty-eight models is running."
    },
    {
      "rate": "a",
      "id": "color",
      "name": "Color",
      "min": 0,
      "max": 1,
      "default": 0.5,
      "group": "Oscillator",
      "description": "The second model control, usually the brighter-or-darker one. It also means something different in each model."
    },
    {
      "rate": "a",
      "id": "attack",
      "name": "Attack",
      "min": 0,
      "max": 1,
      "default": 0,
      "group": "Envelope",
      "description": "The module's own attack-decay envelope, which is what stops a sustained shape droning."
    },
    {
      "rate": "a",
      "id": "decay",
      "name": "Decay",
      "min": 0,
      "max": 1,
      "default": 0.4,
      "group": "Envelope",
      "description": "The module\u2019s own attack-decay envelope, which is what stops a sustained model droning between notes."
    }
  ]
});

export const PEAKS = defineDevice({
  "id": "Peaks",
  "kind": "synth",
  "version": 1,
  "description": "The four drum models from Peaks: a bass drum, a snare, a hi-hat and an FM drum, each struck by a note.",
  "vendor": "Mutable Instruments",
  "license": "MIT",
  "source": "https://github.com/pichenettes/eurorack (peaks)",
  "build": "wasm",
  "processor": "poptart-wasm-peaks",
  "channels": {
    "in": 0,
    "out": 2
  },
  "params": [
    {
      "rate": "k",
      "id": "voice",
      "name": "Voice",
      "default": 0,
      "options": [
        "Bass Drum",
        "Snare Drum",
        "Hi-Hat",
        "FM Drum"
      ],
      "group": "Drum",
      "description": "Which of the module's four drum models is struck. The four controls below mean something a little different in each."
    },
    {
      "rate": "a",
      "id": "frequency",
      "name": "Frequency",
      "min": 0,
      "max": 1,
      "default": 0.5,
      "group": "Drum",
      "description": "The pitch of the drum, an octave either way around the note played. The bass drum and the snare reach seven semitones either side of their own center, so a note far from it is heard at the edge of the range."
    },
    {
      "rate": "a",
      "id": "punch",
      "name": "Punch",
      "min": 0,
      "max": 1,
      "default": 0.5,
      "group": "Drum",
      "description": "How hard the drum is hit: the depth of the pitch sweep at the start and the weight behind it."
    },
    {
      "rate": "a",
      "id": "tone",
      "name": "Tone",
      "min": 0,
      "max": 1,
      "default": 0.5,
      "group": "Drum",
      "description": "The brightness of the drum - how much top the body and the transient keep."
    },
    {
      "rate": "a",
      "id": "decay",
      "name": "Decay",
      "min": 0,
      "max": 1,
      "default": 0.4,
      "group": "Drum",
      "description": "How long the drum rings on after it is struck."
    }
  ]
});

export const CLOUDS = defineDevice({
  "id": "Clouds",
  "kind": "fx",
  "version": 1,
  "description": "A granular processor: it keeps a few seconds of what went through it and plays that back as grains, or stretches it, or rebuilds it from its spectrum.",
  "vendor": "Mutable Instruments",
  "license": "MIT",
  "source": "https://github.com/pichenettes/eurorack (clouds)",
  "build": "wasm",
  "processor": "poptart-wasm-clouds",
  "channels": {
    "in": 2,
    "out": 2
  },
  "params": [
    {
      "rate": "k",
      "id": "mode",
      "name": "Mode",
      "default": 0,
      "options": [
        "Granular",
        "Stretch",
        "Looping Delay",
        "Spectral"
      ],
      "group": "Buffer",
      "description": "Granular scatters grains; stretch holds and smears; looping delay is a delay you can freeze; spectral rebuilds the sound from its own spectrum."
    },
    {
      "rate": "a",
      "id": "position",
      "name": "Position",
      "min": 0,
      "max": 1,
      "default": 0.5,
      "group": "Buffer",
      "description": "Where in the recorded buffer the grains are read from. Hold it still and the sound freezes there; sweep it and the buffer is scrubbed."
    },
    {
      "rate": "a",
      "id": "size",
      "name": "Size",
      "min": 0,
      "max": 1,
      "default": 0.5,
      "group": "Buffer",
      "description": "How long each grain is, from a click to most of a second. Short grains read as texture, long ones as the sound itself."
    },
    {
      "rate": "a",
      "id": "density",
      "name": "Density",
      "min": 0,
      "max": 1,
      "default": 0.75,
      "group": "Buffer",
      "description": "How often a grain is thrown. The middle is silence; below it they come at random, above it in step."
    },
    {
      "rate": "a",
      "id": "texture",
      "name": "Texture",
      "min": 0,
      "max": 1,
      "default": 0.5,
      "group": "Buffer",
      "description": "The shape of the window each grain is played through, from soft and smooth to hard-edged and clicky."
    },
    {
      "rate": "a",
      "id": "pitch",
      "name": "Pitch",
      "min": -24,
      "max": 24,
      "default": 0,
      "unit": "st",
      "group": "Buffer",
      "description": "How far the grains are transposed, in semitones."
    },
    {
      "rate": "a",
      "id": "freeze",
      "name": "Freeze",
      "min": 0,
      "max": 1,
      "default": 0,
      "step": 1,
      "group": "Buffer",
      "description": "Stops writing into the buffer, so what is already in it is all there is to play with."
    },
    {
      "rate": "a",
      "id": "drywet",
      "name": "Mix",
      "min": 0,
      "max": 1,
      "default": 0.5,
      "group": "Output",
      "description": "The untouched signal against the cloud."
    },
    {
      "rate": "a",
      "id": "spread",
      "name": "Stereo Spread",
      "min": 0,
      "max": 1,
      "default": 0.5,
      "group": "Output",
      "description": "How far grains are panned either way."
    },
    {
      "rate": "a",
      "id": "feedback",
      "name": "Feedback",
      "min": 0,
      "max": 1,
      "default": 0,
      "group": "Output",
      "description": "How much of the output is written back into the buffer, which is how a cloud builds on itself rather than only on what is played in."
    },
    {
      "rate": "a",
      "id": "reverb",
      "name": "Reverb",
      "min": 0,
      "max": 1,
      "default": 0,
      "group": "Output",
      "description": "The reverb built into the module, after the grains."
    }
  ]
});

// Warps is not here. Its cross-modulator wants a carrier patched into it with `.audio()`, and
// after two rounds of fixing the wrapper it still produced digital noise across most of its
// algorithm range; the Wavetable's own FM/PM/ring warp modes cover what it was here for. The
// build still knows how to compile it (see build/devices) if it is ever worth another go.
export const MUTABLE_DEVICES = Object.freeze([PLAITS, RINGS, ELEMENTS, BRAIDS, PEAKS, CLOUDS]);
