// Signalsmith Stretch, as a device descriptor.
//
// GENERATED by build/devices/build-devices.mjs from the upstream sources pinned in
// devices.lock.json - do not edit.
//
// Only the pitch half of the library is exposed; the reason is in build/devices/stretch.mjs.
// 
// MIT, copyright Signalsmith Audio Ltd.

import { defineDevice } from '../descriptor.mjs';

export const SHIFT = defineDevice({
  "id": "Shift",
  "kind": "fx",
  "version": 1,
  "description": "Pitch shifting that keeps time, with separate control of the formants.",
  "vendor": "Signalsmith Audio",
  "license": "MIT",
  "source": "https://github.com/Signalsmith-Audio/signalsmith-stretch",
  "build": "wasm",
  "processor": "poptart-wasm-shift",
  "channels": {
    "in": 2,
    "out": 2
  },
  "params": [
    {
      "id": "pitch",
      "name": "Pitch",
      "min": -24,
      "max": 24,
      "default": 0,
      "unit": "st",
      "group": "Shift",
      "description": "Transposition in semitones. Whole numbers are the musical intervals; in between is a detune.",
      "rate": "a"
    },
    {
      "id": "formant",
      "name": "Formant",
      "min": -12,
      "max": 12,
      "default": 0,
      "unit": "st",
      "group": "Shift",
      "description": "Moves the resonances without moving the pitch. Set it against the pitch to keep a voice from sounding like a chipmunk.",
      "rate": "a"
    },
    {
      "id": "tonality",
      "name": "Tonality Limit",
      "min": 0,
      "max": 16000,
      "default": 8000,
      "unit": "Hz",
      "group": "Shift",
      "description": "Above this, partials keep their own frequency rather than being transposed, which is what keeps sibilance from shifting with the note. Zero transposes everything.",
      "rate": "k"
    }
  ]
});

export const STRETCH_DEVICES = Object.freeze([SHIFT]);
